package:
    name: pyg-timeseries
    version: 0.0.4

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base      >=0.0.3
        - numba         >=0.48.0
        - bottleneck    >=1.3.2
    run:
        - pyg-base      >=0.0.3
        - numba         >=0.48.0
        - bottleneck    >=1.3.2

about:
    home: https://github.com/gityoav/pyg-timeseries
    license: GNU